export const CHANGE_SEARCHFIELD: string = 'CHANGE_SEARCHFIELD';

export const REQUEST_ROBOTS_PENDING: string = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS: string = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED: string = 'REQUEST_ROBOTS_FAILED';